--Query type: DDL
ALTER DATABASE [database_name]
SET QUERY_STORE = ON;

ALTER DATABASE [database_name]
SET QUERY_STORE (
    CLEANUP_POLICY = (
        STALE_QUERY_THRESHOLD_DAYS = 90
    ),
    DATA_FLUSH_INTERVAL_SECONDS = 900,
    MAX_STORAGE_SIZE_MB = 1024
);
