--Query type: DDL
WITH QueryStoreSettings AS (
    SELECT 'READ_WRITE' AS OPERATION_MODE,
           90 AS STALE_QUERY_THRESHOLD_DAYS,
           900 AS DATA_FLUSH_INTERVAL_SECONDS,
           1024 AS MAX_STORAGE_SIZE_MB,
           60 AS INTERVAL_LENGTH_MINUTES,
           'AUTO' AS SIZE_BASED_CLEANUP_MODE,
           200 AS MAX_PLANS_PER_QUERY,
           'ON' AS WAIT_STATS_CAPTURE_MODE
)
SELECT *
FROM QueryStoreSettings;
