--Query type: DDL
ALTER DATABASE [new_database_name]
SET QUERY_STORE = ON (
    OPERATION_MODE = READ_ONLY,
    CLEANUP_POLICY = (
        STALE_QUERY_THRESHOLD_DAYS = 30
    ),
    DATA_FLUSH_INTERVAL_SECONDS = 300,
    QUERY_CAPTURE_MODE = ALL,
    MAX_STORAGE_SIZE_MB = 512,
    INTERVAL_LENGTH_MINUTES = 30
);
-- REMORPH CLEANUP: DROP DATABASE [new_database_name];
