-- tsql sql:
ALTER DATABASE [new_database_name]
SET QUERY_STORE = ON (
    OPERATION_MODE = READ_WRITE,
    CLEANUP_POLICY = (
        STALE_QUERY_THRESHOLD_DAYS = 90
    ),
    DATA_FLUSH_INTERVAL_SECONDS = 900,
    QUERY_CAPTURE_MODE = AUTO,
    MAX_STORAGE_SIZE_MB = 1024,
    INTERVAL_LENGTH_MINUTES = 60
);
-- REMORPH CLEANUP: DROP DATABASE [new_database_name];
