--Query type: DDL
CREATE TABLE Customer (CUSTKEY INTEGER PRIMARY KEY, NAME VARCHAR(100), ADDRESS VARCHAR(100));
INSERT INTO Customer (CUSTKEY, NAME, ADDRESS)
SELECT *
FROM (VALUES (1, 'John', '123 Main St')) AS temp_table(CUSTKEY, NAME, ADDRESS);
SELECT *
FROM Customer;
-- REMORPH CLEANUP: DROP TABLE Customer;
