-- tsql sql:
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'new_strong_password';
CREATE DATABASE SCOPED CREDENTIAL [NewWorkspaceIdentity]
    WITH IDENTITY = 'NewManagedIdentity';
-- REMORPH CLEANUP: DROP MASTER KEY;
-- REMORPH CLEANUP: DROP DATABASE SCOPED CREDENTIAL [NewWorkspaceIdentity];
