-- tsql sql:
CREATE TABLE Region (
    RegionKey INT NOT NULL PRIMARY KEY CLUSTERED,
    RegionName VARCHAR(50) NOT NULL,
    RegionComment VARCHAR(255) NULL,
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
) WITH (SYSTEM_VERSIONING = ON);
