--Query type: DQL
WITH DateFunctions AS (
    SELECT
        SYSDATETIME() AS SYSDATETIME,
        SYSDATETIMEOFFSET() AS SYSDATETIMEOFFSET,
        SYSUTCDATETIME() AS SYSUTCDATETIME,
        CURRENT_TIMESTAMP AS CURRENT_TIMESTAMP_VALUE,
        GETDATE() AS GETDATE,
        GETUTCDATE() AS GETUTCDATE
)
SELECT
    SYSDATETIME,
    SYSDATETIMEOFFSET,
    SYSUTCDATETIME,
    CURRENT_TIMESTAMP_VALUE,
    GETDATE,
    GETUTCDATE
FROM DateFunctions
