--Query type: DDL
ALTER COLUMN ENCRYPTION KEY MyNewCEK
ADD VALUE
(
    COLUMN_MASTER_KEY = MyNewCMK,
    ALGORITHM = 'RSA_OAEP',
    ENCRYPTED_VALUE = 0x1234567890ABCDEF
);
-- REMORPH CLEANUP: DROP COLUMN ENCRYPTION KEY MyNewCEK;
-- REMORPH CLEANUP: DROP COLUMN MASTER KEY MyNewCMK;