-- snowflake sql:
select seq1(), seq2(), seq8(), seq4() from SANDBOX.LABS.PRODUCT_SRC;

-- databricks sql:
SELECT
  MONOTONICALLY_INCREASING_ID(),
  MONOTONICALLY_INCREASING_ID(),
  MONOTONICALLY_INCREASING_ID(),
  MONOTONICALLY_INCREASING_ID()
FROM SANDBOX.LABS.PRODUCT_SRC;