-- tsql sql:
CREATE PARTITION FUNCTION myNewRangePF (INT) AS RANGE LEFT FOR VALUES (5, 500, 5000);
CREATE PARTITION SCHEME myNewRangePS AS PARTITION myNewRangePF ALL TO ('PRIMARY');
CREATE TABLE myTable (id INT, value INT) ON myNewRangePS (id);
INSERT INTO myTable (id, value) VALUES (1, 10), (6, 60), (501, 5010);
SELECT * FROM myTable;
-- REMORPH CLEANUP: DROP TABLE myTable; DROP PARTITION SCHEME myNewRangePS; DROP PARTITION FUNCTION myNewRangePF;
