--Query type: DDL
SELECT CUSTKEY, NAME INTO #TempTable FROM (VALUES (1, 'John')) AS Temp(CUSTKEY, NAME);
ALTER TABLE #TempTable ENABLE CHANGE_TRACKING;
SELECT * FROM #TempTable;
-- REMORPH CLEANUP: DROP TABLE #TempTable;
