--Query type: DML
CREATE TABLE #Customer
(
    CUSTKEY INT,
    NATIONKEY INT,
    TOTALPURCHASE DECIMAL(10, 2)
);

CREATE TABLE #Nation
(
    NATIONKEY INT,
    REGIONKEY INT,
    TOTALSALES DECIMAL(10, 2)
);

INSERT INTO #Customer (CUSTKEY, NATIONKEY, TOTALPURCHASE)
VALUES
    (1, 1, 100.00),
    (2, 2, 200.00),
    (3, 1, 300.00);

INSERT INTO #Nation (NATIONKEY, REGIONKEY, TOTALSALES)
VALUES
    (1, 1, 1000.00),
    (2, 2, 2000.00);

WITH CustomerCTE AS
(
    SELECT CUSTKEY, NATIONKEY, TOTALPURCHASE
    FROM #Customer
),
NationCTE AS
(
    SELECT NATIONKEY, REGIONKEY, TOTALSALES
    FROM #Nation
)
UPDATE c
SET c.TOTALPURCHASE = c.TOTALPURCHASE + n.TOTALSALES
FROM CustomerCTE c
INNER JOIN NationCTE n ON c.NATIONKEY = n.NATIONKEY;

SELECT *
FROM #Customer;

-- REMORPH CLEANUP: DROP TABLE #Customer;
-- REMORPH CLEANUP: DROP TABLE #Nation;