--Query type: DQL
DECLARE @ORDERDATE DATETIME = GETDATE();
DECLARE @ORDERTIME TIME;

WITH ORDERS AS (
  SELECT CONVERT(time, @ORDERDATE) AS ORDERTIME
)
SELECT ORDERTIME AS 'Order Time', @ORDERDATE AS 'Order Date Time'
FROM ORDERS