# See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# and https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Feature Request
description: Something new needs to happen with Lakebridge
title: "[FEATURE]: "
labels: ["needs-triage"]
type: "feature"

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature request you're willing to submit
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: category
    attributes:
      label: Category of feature request
      description: Please select the category that best describes the feature you are requesting for.
      options:
        - Profiler
        - Analyzer
        - Transpiler
        - Reconcile
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem statement
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, references or screenshots about the feature request here.
    validations:
      required: false
