--Query type: DDL
CREATE TABLE [HR].[EmployeesHistory]
(
    EmployeeID INT NOT NULL,
    Salary MONEY NOT NULL,
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
);

CREATE TABLE [HR].[Employees]
(
    EmployeeID INT NOT NULL,
    Salary MONEY NOT NULL,
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
);

INSERT INTO [HR].[Employees] (EmployeeID, Salary, ValidFrom, ValidTo)
VALUES (1, 10000, CAST('2022-01-01' AS DATETIME2), CAST('2022-01-02' AS DATETIME2));

ALTER TABLE [HR].[Employees] ADD CONSTRAINT PK_Employees PRIMARY KEY (EmployeeID);

ALTER TABLE [HR].[Employees]
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [HR].[EmployeesHistory], DATA_CONSISTENCY_CHECK = ON));

SELECT * FROM [HR].[Employees];

-- REMORPH CLEANUP: DROP TABLE [HR].[EmployeesHistory];
-- REMORPH CLEANUP: DROP TABLE [HR].[Employees];