--Query type: DDL
CREATE TABLE #REGION_INDEX (R_REGIONKEY INT, R_NAME VARCHAR(50));
INSERT INTO #REGION_INDEX (R_REGIONKEY, R_NAME)
VALUES ('1', 'Region1'), ('2', 'Region2');
CREATE NONCLUSTERED INDEX IX_REGION_INDEX ON #REGION_INDEX (R_REGIONKEY, R_NAME) WITH (DATA_COMPRESSION = ROW);
SELECT * FROM #REGION_INDEX;
-- REMORPH CLEANUP: DROP TABLE #REGION_INDEX;
