-- tsql sql:
CREATE TABLE #TempTable (C1 VARCHAR(10), C2 VARCHAR(10));
INSERT INTO #TempTable (C1, C2)
VALUES ('1', 'a'), ('2', 'b');
CREATE NONCLUSTERED INDEX IX_INDEX_2 ON #TempTable (C2)
WITH (XML_COMPRESSION = ON);
SELECT * FROM #TempTable;
-- REMORPH CLEANUP: DROP TABLE #TempTable;
-- REMORPH CLEANUP: DROP INDEX IX_INDEX_2 ON #TempTable;
