--Query type: DML
WITH dates AS (
  SELECT CAST('2022-01-01' AS DATE) AS d
  UNION ALL
  SELECT CAST('2022-01-02' AS DATE) AS d
  UNION ALL
  SELECT CAST('2022-01-03' AS DATE) AS d
)
SELECT 
  d AS [Date], 
  DATENAME(WEEKDAY, d) AS [Day], 
  DATEPART(WEEK, d) AS [WOY], 
  DATEPART(ISOWW, d) AS [WOY (ISO)], 
  DATEPART(YEAR, d) AS [YOW], 
  DATEPART(YEAR, d) + CASE WHEN DATEPART(ISOWW, d) = 1 AND MONTH(d) = 12 THEN 1 ELSE 0 END AS [YOW (ISO)]
FROM dates;