-- tsql sql:
CREATE TABLE TempTable (ID INT, Name VARCHAR(50));
INSERT INTO TempTable (ID, Name)
VALUES (1, 'John Doe'), (2, 'Jane Doe');
ALTER TABLE TempTable ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
SELECT * FROM TempTable;
-- REMORPH CLEANUP: DROP TABLE TempTable;
