--Query type: DDL
SELECT L_ORDERKEY, L_PARTKEY INTO #temp FROM (VALUES (1, 1), (2, 2)) AS lineitem(L_ORDERKEY, L_PARTKEY);
CREATE STATISTICS OrderLineStats ON #temp (L_ORDERKEY, L_PARTKEY) WITH FULLSCAN, NORECOMPUTE;
SELECT * FROM #temp;
-- REMORPH CLEANUP: DROP TABLE #temp;
