-- tsql sql:
CREATE DATABASE TPC_H_DB;
ALTER DATABASE TPC_H_DB ADD FILE (
    NAME = TPC_H_FILE1,
    FILENAME = 'C:\TPC_H_FILE1.mdf',
    SIZE = 5MB,
    MAXSIZE = 100MB,
    FILEGROWTH = 5MB
);
SELECT * FROM sys.master_files WHERE database_id = DB_ID('TPC_H_DB');
-- REMORPH CLEANUP: DROP DATABASE TPC_H_DB;
