--Query type: DDL
CREATE TABLE CUSTOMER_SPARSE
(
    C_CUSTKEY INT PRIMARY KEY,
    C_NAME VARCHAR(50) SPARSE NULL,
    C_NATIONKEY INT SPARSE NULL,
    C_ACCTBAL DECIMAL(15, 2)
);

WITH temp AS
(
    SELECT 1 AS C_CUSTKEY, CAST('Name' AS VARCHAR(50)) AS C_NAME, 1 AS C_NATIONKEY, CAST(0.00 AS DECIMAL(15, 2)) AS C_ACCTBAL
)
INSERT INTO CUSTOMER_SPARSE (C_CUSTKEY, C_NAME, C_NATIONKEY, C_ACCTBAL)
SELECT * FROM temp;

SELECT * FROM CUSTOMER_SPARSE;

-- REMORPH CLEANUP: DROP TABLE CUSTOMER_SPARSE;