package com.databricks.labs.remorph.parsers

// TODO: Valentin some dialects will be loaded via external jars - sealed traits could be an issue?
sealed trait KeywordType
case object Reserved extends KeywordType
case object NonReserved extends KeywordType

sealed trait KeywordClass
case object SyntaxKeyword extends KeywordClass
case object OptionKeyword extends KeywordClass
case object FunctionKeyword extends KeywordClass
case object XMLOption extends KeywordClass
// etc...

sealed trait OptionType

/**
 * An option that is ON if present
 */
case object BooleanOption extends OptionType

/**
 * An option that requires some value to be present. Note that the value will be accepted from an expression. The actual
 * value could be checked to see that it yields the correct type, but in this transpiler we assume valid input in the
 * first place.
 */
case object ExpressionOption extends OptionType

/**
 * The type of the value that the option takes. This is useful for validation and transformation.
 */
sealed trait OptionValueType

/**
 * The option does not take a value, usually present or not present
 */
case object NoValue extends OptionValueType

/**
 * The option takes a string value only
 */
case object StringValue extends OptionValueType

/**
 * An option that takes an integer value only
 */
case object IntegerValue extends OptionValueType
// etc ...

// TODO: Maybe the use of Option is not the best choice here, as it is a Scala type and could be confusing?

case class Keyword(
    keywordType: KeywordType, // Whether the keyword is reserved or non-reserved (can be useful for transformation)
    keywordClass: KeywordClass, // The class of the keyword (e.g. OPTION, XMLOPTION and so on )
    optionType: Option[OptionType] = None, // The type of the option if the keyword is an option
    optionValueType: Option[OptionValueType] = None // The type of the value that the option takes
) {}

/**
 * <p> This class is used to resolve keywords in the SQL dialects. Keywords that are merely options specifications are
 * not tracked in the lexer and parser as it just involves a lot of clutter and creates huge NFAs and DFAs for no good
 * reason. <p> This type of resolution is useful for the following:
 *   - validation of option names and values
 *   - error reporting - e.g. "OPTION 'foo' is not valid here", "'foo' is not a valid value for 'bar'"
 *   - Perhaps it could also hold the IR representation of the keyword if useful for option values for instance
 * <p> NOTE: This implementation is just a place holder so we do not lose track of the myriad keywords in the dialects
 * but the actual implementation is TBD.
 */
abstract class KeywordResolver {

  protected val commonKeywordsPf: PartialFunction[String, Keyword] = {
    case "ABORT" => Keyword(NonReserved, SyntaxKeyword)
    case "ACCESS" => Keyword(NonReserved, SyntaxKeyword)
    case "ACCOUNT" => Keyword(NonReserved, SyntaxKeyword)
    case "ACTION" => Keyword(NonReserved, SyntaxKeyword)
    case "ADD" => Keyword(NonReserved, SyntaxKeyword)
    case "AES" => Keyword(NonReserved, SyntaxKeyword)
    case "AFTER" => Keyword(NonReserved, SyntaxKeyword)
    case "ALL" => Keyword(NonReserved, SyntaxKeyword)
    case "ALLOW" => Keyword(NonReserved, SyntaxKeyword)
    case "ALLOWED" => Keyword(NonReserved, SyntaxKeyword)
    case "ALTER" => Keyword(NonReserved, SyntaxKeyword)
    case "ALWAYS" => Keyword(NonReserved, SyntaxKeyword)
    case "AN" => Keyword(NonReserved, SyntaxKeyword)
    case "AND" => Keyword(NonReserved, SyntaxKeyword)
    case "ANY" => Keyword(NonReserved, SyntaxKeyword)
    case "APPEND" => Keyword(NonReserved, SyntaxKeyword)
    case "APPLICATION" => Keyword(NonReserved, SyntaxKeyword)
    case "APPLY" => Keyword(NonReserved, SyntaxKeyword)
    case "ARISING" => Keyword(NonReserved, SyntaxKeyword)
    case "ARRAY" => Keyword(NonReserved, SyntaxKeyword)
    case "AS" => Keyword(NonReserved, SyntaxKeyword)
    case "ASC" => Keyword(NonReserved, SyntaxKeyword)
    case "AT" => Keyword(NonReserved, SyntaxKeyword)
    case "AUTHORIZATION" => Keyword(NonReserved, SyntaxKeyword)
    case "AUTHORS" => Keyword(NonReserved, SyntaxKeyword)
    case "AUTO" => Keyword(NonReserved, SyntaxKeyword)
    case "BASE" => Keyword(NonReserved, SyntaxKeyword)
    case "BE" => Keyword(NonReserved, SyntaxKeyword)
    case "BEFORE" => Keyword(NonReserved, SyntaxKeyword)
    case "BEGIN" => Keyword(NonReserved, SyntaxKeyword)
    case "BETWEEN" => Keyword(NonReserved, SyntaxKeyword)
    case "BIGINT" => Keyword(NonReserved, SyntaxKeyword)
    case "BINARY" => Keyword(NonReserved, SyntaxKeyword)
    case "BLOCK" => Keyword(NonReserved, SyntaxKeyword)
    case "BRACKET" => Keyword(NonReserved, SyntaxKeyword)
    case "BUT" => Keyword(NonReserved, SyntaxKeyword)
    case "BY" => Keyword(NonReserved, SyntaxKeyword)
    case "CALLED" => Keyword(NonReserved, SyntaxKeyword)
    case "CALLER" => Keyword(NonReserved, SyntaxKeyword)
    case "CASCADE" => Keyword(NonReserved, SyntaxKeyword)
    case "CASE" => Keyword(NonReserved, SyntaxKeyword)
    case "CAST" => Keyword(NonReserved, SyntaxKeyword)
    case "CHANGE" => Keyword(NonReserved, SyntaxKeyword)
    case "CHANGES" => Keyword(NonReserved, SyntaxKeyword)
    case "CHECK" => Keyword(NonReserved, SyntaxKeyword)
    case "CHECKSUM" => Keyword(NonReserved, SyntaxKeyword)
    case "CLAIM" => Keyword(NonReserved, SyntaxKeyword)
    case "CLUSTER" => Keyword(NonReserved, SyntaxKeyword)
    case "COLLATE" => Keyword(NonReserved, SyntaxKeyword)
    case "COLLECTION" => Keyword(NonReserved, SyntaxKeyword)
    case "COLON" => Keyword(NonReserved, SyntaxKeyword)
    case "COLUMN" => Keyword(NonReserved, SyntaxKeyword)
    case "COLUMNS" => Keyword(NonReserved, SyntaxKeyword)
    case "COMMA" => Keyword(NonReserved, SyntaxKeyword)
    case "COMMIT" => Keyword(NonReserved, SyntaxKeyword)
    case "COMPRESS" => Keyword(NonReserved, SyntaxKeyword)
    case "COMPRESSION" => Keyword(NonReserved, SyntaxKeyword)
    case "CONDITION" => Keyword(NonReserved, SyntaxKeyword)
    case "CONFIGURATION" => Keyword(NonReserved, SyntaxKeyword)
    case "CONNECT" => Keyword(NonReserved, SyntaxKeyword)
    case "CONNECTION" => Keyword(NonReserved, SyntaxKeyword)
    case "CONNECTIONS" => Keyword(NonReserved, SyntaxKeyword)
    case "CONSTRAINT" => Keyword(NonReserved, SyntaxKeyword)
    case "CONTAINS" => Keyword(NonReserved, SyntaxKeyword)
    case "CONTEXT" => Keyword(NonReserved, SyntaxKeyword)
    case "CONTINUE" => Keyword(NonReserved, SyntaxKeyword)
    case "CONTRACT" => Keyword(NonReserved, SyntaxKeyword)
    case "COPY" => Keyword(NonReserved, SyntaxKeyword)
    case "COPYRIGHT" => Keyword(NonReserved, SyntaxKeyword)
    case "CREATE" => Keyword(NonReserved, SyntaxKeyword)
    case "CREATION" => Keyword(NonReserved, SyntaxKeyword)
    case "CROSS" => Keyword(NonReserved, SyntaxKeyword)
    case "CUBE" => Keyword(NonReserved, SyntaxKeyword)
    case "CURRENT" => Keyword(NonReserved, SyntaxKeyword)
    case "DAMAGES" => Keyword(NonReserved, SyntaxKeyword)
    case "DATA" => Keyword(NonReserved, SyntaxKeyword)
    case "DATABASE" => Keyword(NonReserved, SyntaxKeyword)
    case "DATE" => Keyword(NonReserved, SyntaxKeyword)
    case "DAYS" => Keyword(NonReserved, SyntaxKeyword)
    case "DDL" => Keyword(NonReserved, SyntaxKeyword)
    case "DEALINGS" => Keyword(NonReserved, SyntaxKeyword)
    case "DEFAULT" => Keyword(NonReserved, SyntaxKeyword)
    case "DEFINITION" => Keyword(NonReserved, SyntaxKeyword)
    case "DELAY" => Keyword(NonReserved, OptionKeyword, Some(ExpressionOption), Some(IntegerValue))
    case "DELETE" => Keyword(NonReserved, SyntaxKeyword)
    case "DESC" => Keyword(NonReserved, SyntaxKeyword)
    case "DIGIT" => Keyword(NonReserved, SyntaxKeyword)
    case "DIRECTORY" => Keyword(NonReserved, SyntaxKeyword)
    case "DISABLE" => Keyword(NonReserved, SyntaxKeyword)
    case "DISABLED" => Keyword(NonReserved, SyntaxKeyword)
    case "DISTINCT" => Keyword(NonReserved, SyntaxKeyword)
    case "DOLLAR" => Keyword(NonReserved, SyntaxKeyword)
    case "DOT" => Keyword(NonReserved, SyntaxKeyword)
    case "DOUBLE" => Keyword(NonReserved, SyntaxKeyword)
    case "DROP" => Keyword(NonReserved, SyntaxKeyword)
    case "DYNAMIC" => Keyword(NonReserved, SyntaxKeyword)
    case "ELSE" => Keyword(NonReserved, SyntaxKeyword)
    case "EMPTY" => Keyword(NonReserved, SyntaxKeyword)
    case "ENABLE" => Keyword(NonReserved, SyntaxKeyword)
    case "ENABLED" => Keyword(NonReserved, SyntaxKeyword)
    case "ENCRYPTION" => Keyword(NonReserved, SyntaxKeyword)
    case "END" => Keyword(NonReserved, SyntaxKeyword)
    case "ENDPOINT" => Keyword(NonReserved, SyntaxKeyword)
    case "EOF" => Keyword(NonReserved, SyntaxKeyword)
    case "EQ" => Keyword(NonReserved, SyntaxKeyword)
    case "ERROR" => Keyword(NonReserved, SyntaxKeyword)
    case "ESCAPE" => Keyword(NonReserved, SyntaxKeyword)
    case "EVENT" => Keyword(NonReserved, SyntaxKeyword)
    case "EXCEPT" => Keyword(NonReserved, SyntaxKeyword)
    case "EXECUTE" => Keyword(NonReserved, SyntaxKeyword)
    case "EXISTS" => Keyword(NonReserved, SyntaxKeyword)
    case "EXPIRY" => Keyword(NonReserved, SyntaxKeyword)
    case "EXPRESS" => Keyword(NonReserved, SyntaxKeyword)
    case "EXTENSION" => Keyword(NonReserved, SyntaxKeyword)
    case "EXTERNAL" => Keyword(NonReserved, SyntaxKeyword)
    case "FAILOVER" => Keyword(NonReserved, SyntaxKeyword)
    case "FETCH" => Keyword(NonReserved, SyntaxKeyword)
    case "FILE" => Keyword(NonReserved, SyntaxKeyword)
    case "FILES" => Keyword(NonReserved, SyntaxKeyword)
    case "FIRST" => Keyword(NonReserved, SyntaxKeyword)
    case "FITNESS" => Keyword(NonReserved, SyntaxKeyword)
    case "FLOAT" => Keyword(NonReserved, SyntaxKeyword)
    case "FOLLOWING" => Keyword(NonReserved, SyntaxKeyword)
    case "FOR" => Keyword(NonReserved, SyntaxKeyword)
    case "FORCE" => Keyword(NonReserved, SyntaxKeyword)
    case "FOREIGN" => Keyword(NonReserved, SyntaxKeyword)
    case "FORMAT" => Keyword(NonReserved, SyntaxKeyword)
    case "FROM" => Keyword(NonReserved, SyntaxKeyword)
    case "FULL" => Keyword(NonReserved, SyntaxKeyword)
    case "FUNCTION" => Keyword(NonReserved, SyntaxKeyword)
    case "GET" => Keyword(NonReserved, SyntaxKeyword)
    case "GLOBAL" => Keyword(NonReserved, SyntaxKeyword)
    case "GRANT" => Keyword(NonReserved, SyntaxKeyword)
    case "GROUP" => Keyword(NonReserved, SyntaxKeyword)
    case "GROUPING" => Keyword(NonReserved, SyntaxKeyword)
    case "GROUPS" => Keyword(NonReserved, SyntaxKeyword)
    case "GT" => Keyword(NonReserved, SyntaxKeyword)
    case "HASH" => Keyword(NonReserved, SyntaxKeyword)
    case "HAVING" => Keyword(NonReserved, SyntaxKeyword)
    case "HEX" => Keyword(NonReserved, SyntaxKeyword)
    case "HOLDERS" => Keyword(NonReserved, SyntaxKeyword)
    case "ID" => Keyword(NonReserved, SyntaxKeyword)
    case "IDENTIFIER" => Keyword(NonReserved, SyntaxKeyword)
    case "IDENTITY" => Keyword(NonReserved, SyntaxKeyword)
    case "IF" => Keyword(NonReserved, SyntaxKeyword)
    case "IGNORE" => Keyword(NonReserved, SyntaxKeyword)
    case "IMMEDIATE" => Keyword(NonReserved, SyntaxKeyword)
    case "IMPLICIT" => Keyword(NonReserved, SyntaxKeyword)
    case "IMPLIED" => Keyword(NonReserved, SyntaxKeyword)
    case "IN" => Keyword(NonReserved, SyntaxKeyword)
    case "INCLUDING" => Keyword(NonReserved, SyntaxKeyword)
    case "INCREMENT" => Keyword(NonReserved, SyntaxKeyword)
    case "INDEX" => Keyword(NonReserved, SyntaxKeyword)
    case "INNER" => Keyword(NonReserved, SyntaxKeyword)
    case "INPUT" => Keyword(NonReserved, SyntaxKeyword)
    case "INSENSITIVE" => Keyword(NonReserved, SyntaxKeyword)
    case "INSERT" => Keyword(NonReserved, SyntaxKeyword)
    case "INT" => Keyword(NonReserved, SyntaxKeyword)
    case "INTERSECT" => Keyword(NonReserved, SyntaxKeyword)
    case "INTO" => Keyword(NonReserved, SyntaxKeyword)
    case "IP" => Keyword(NonReserved, SyntaxKeyword)
    case "IS" => Keyword(NonReserved, SyntaxKeyword)
    case "ISOLATION" => Keyword(NonReserved, SyntaxKeyword)
    case "JOIN" => Keyword(NonReserved, SyntaxKeyword)
    case "JSON" => Keyword(NonReserved, SyntaxKeyword)
    case "KEEP" => Keyword(NonReserved, SyntaxKeyword)
    case "KEY" => Keyword(NonReserved, SyntaxKeyword)
    case "KEYS" => Keyword(NonReserved, SyntaxKeyword)
    case "KEYWORD" => Keyword(NonReserved, SyntaxKeyword)
    case "KIND" => Keyword(NonReserved, SyntaxKeyword)
    case "LANGUAGE" => Keyword(NonReserved, SyntaxKeyword)
    case "LAST" => Keyword(NonReserved, SyntaxKeyword)
    case "LEFT" => Keyword(NonReserved, SyntaxKeyword)
    case "LEVEL" => Keyword(NonReserved, SyntaxKeyword)
    case "LIABILITY" => Keyword(NonReserved, SyntaxKeyword)
    case "LIABLE" => Keyword(NonReserved, SyntaxKeyword)
    case "LIKE" => Keyword(NonReserved, SyntaxKeyword)
    case "LIMITED" => Keyword(NonReserved, SyntaxKeyword)
    case "LIST" => Keyword(NonReserved, SyntaxKeyword)
    case "LOCAL" => Keyword(NonReserved, SyntaxKeyword)
    case "LOCATION" => Keyword(NonReserved, SyntaxKeyword)
    case "LOCK" => Keyword(NonReserved, SyntaxKeyword)
    case "LOCKS" => Keyword(NonReserved, SyntaxKeyword)
    case "LOG" => Keyword(NonReserved, SyntaxKeyword)
    case "LOGIN" => Keyword(NonReserved, SyntaxKeyword)
    case "LT" => Keyword(NonReserved, SyntaxKeyword)
    case "MARK" => Keyword(NonReserved, SyntaxKeyword)
    case "MASTER" => Keyword(NonReserved, SyntaxKeyword)
    case "MATCHED" => Keyword(NonReserved, SyntaxKeyword)
    case "MATERIALIZED" => Keyword(NonReserved, SyntaxKeyword)
    case "MAX" => Keyword(NonReserved, SyntaxKeyword)
    case "MEDIUM" => Keyword(NonReserved, SyntaxKeyword)
    case "MEMORY" => Keyword(NonReserved, SyntaxKeyword)
    case "MERCHANTABILITY" => Keyword(NonReserved, SyntaxKeyword)
    case "MERGE" => Keyword(NonReserved, SyntaxKeyword)
    case "METADATA" => Keyword(NonReserved, SyntaxKeyword)
    case "MIN" => Keyword(NonReserved, SyntaxKeyword)
    case "MINUS" => Keyword(NonReserved, SyntaxKeyword)
    case "MIT" => Keyword(NonReserved, SyntaxKeyword)
    case "MODE" => Keyword(NonReserved, SyntaxKeyword)
    case "MODIFY" => Keyword(NonReserved, SyntaxKeyword)
    case "MOVE" => Keyword(NonReserved, SyntaxKeyword)
    case "MULTI" => Keyword(NonReserved, SyntaxKeyword)
    case "MUST" => Keyword(NonReserved, SyntaxKeyword)
    case "NAME" => Keyword(NonReserved, SyntaxKeyword)
    case "NEXT" => Keyword(NonReserved, SyntaxKeyword)
    case "NO" => Keyword(NonReserved, SyntaxKeyword)
    case "NON" => Keyword(NonReserved, SyntaxKeyword)
    case "NONE" => Keyword(NonReserved, SyntaxKeyword)
    case "NONINFRINGEMENT" => Keyword(NonReserved, SyntaxKeyword)
    case "NOT" => Keyword(NonReserved, SyntaxKeyword)
    case "NOTIFICATION" => Keyword(NonReserved, SyntaxKeyword)
    case "NTILE" => Keyword(NonReserved, SyntaxKeyword)
    case "NULL" => Keyword(NonReserved, SyntaxKeyword)
    case "NULLS" => Keyword(NonReserved, SyntaxKeyword)
    case "NUMBER" => Keyword(NonReserved, SyntaxKeyword)
    case "NUMERIC" => Keyword(NonReserved, SyntaxKeyword)
    case "OBJECT" => Keyword(NonReserved, SyntaxKeyword)
    case "OF" => Keyword(NonReserved, SyntaxKeyword)
    case "OFFSET" => Keyword(NonReserved, SyntaxKeyword)
    case "OLD" => Keyword(NonReserved, SyntaxKeyword)
    case "ON" => Keyword(NonReserved, SyntaxKeyword)
    case "ONLY" => Keyword(NonReserved, SyntaxKeyword)
    case "OPERATION" => Keyword(NonReserved, SyntaxKeyword)
    case "OPTIMIZATION" => Keyword(NonReserved, SyntaxKeyword)
    case "OPTIMIZED" => Keyword(NonReserved, SyntaxKeyword)
    case "OPTION" => Keyword(NonReserved, SyntaxKeyword)
    case "OR" => Keyword(NonReserved, SyntaxKeyword)
    case "ORDER" => Keyword(NonReserved, SyntaxKeyword)
    case "OTHER" => Keyword(NonReserved, SyntaxKeyword)
    case "OTHERWISE" => Keyword(NonReserved, SyntaxKeyword)
    case "OUT" => Keyword(NonReserved, SyntaxKeyword)
    case "OUTER" => Keyword(NonReserved, SyntaxKeyword)
    case "OUTPUT" => Keyword(NonReserved, SyntaxKeyword)
    case "OVER" => Keyword(NonReserved, SyntaxKeyword)
    case "OVERRIDE" => Keyword(NonReserved, SyntaxKeyword)
    case "OWNER" => Keyword(NonReserved, SyntaxKeyword)
    case "OWNERSHIP" => Keyword(NonReserved, SyntaxKeyword)
    case "PAGE" => Keyword(NonReserved, SyntaxKeyword)
    case "PARTIAL" => Keyword(NonReserved, SyntaxKeyword)
    case "PARTICULAR" => Keyword(NonReserved, SyntaxKeyword)
    case "PARTITION" => Keyword(NonReserved, SyntaxKeyword)
    case "PASSWORD" => Keyword(NonReserved, OptionKeyword, Some(ExpressionOption), Some(StringValue))
    case "PATH" => Keyword(NonReserved, SyntaxKeyword)
    case "PER" => Keyword(NonReserved, SyntaxKeyword)
    case "PERCENT" => Keyword(NonReserved, SyntaxKeyword)
    case "PHYSICAL" => Keyword(NonReserved, SyntaxKeyword)
    case "PIVOT" => Keyword(NonReserved, SyntaxKeyword)
    case "PLUS" => Keyword(NonReserved, SyntaxKeyword)
    case "POLICY" => Keyword(NonReserved, SyntaxKeyword)
    case "PORT" => Keyword(NonReserved, SyntaxKeyword)
    case "PRECEDING" => Keyword(NonReserved, SyntaxKeyword)
    case "PRECISION" => Keyword(NonReserved, SyntaxKeyword)
    case "PRIMARY" => Keyword(NonReserved, SyntaxKeyword)
    case "PRIOR" => Keyword(NonReserved, SyntaxKeyword)
    case "PRIVILEGES" => Keyword(NonReserved, SyntaxKeyword)
    case "PROCEDURE" => Keyword(NonReserved, SyntaxKeyword)
    case "PROPERTY" => Keyword(NonReserved, SyntaxKeyword)
    case "PROVIDED" => Keyword(NonReserved, SyntaxKeyword)
    case "PROVIDER" => Keyword(NonReserved, SyntaxKeyword)
    case "PUBLIC" => Keyword(NonReserved, SyntaxKeyword)
    case "PURPOSE" => Keyword(NonReserved, SyntaxKeyword)
    case "PYTHON" => Keyword(NonReserved, SyntaxKeyword)
    case "QUERY" => Keyword(NonReserved, SyntaxKeyword)
    case "QUEUE" => Keyword(NonReserved, SyntaxKeyword)
    case "QUOTE" => Keyword(NonReserved, SyntaxKeyword)
    case "QUOTED" => Keyword(NonReserved, SyntaxKeyword)
    case "RANGE" => Keyword(NonReserved, SyntaxKeyword)
    case "RAW" => Keyword(NonReserved, SyntaxKeyword)
    case "READ" => Keyword(NonReserved, SyntaxKeyword)
    case "REAL" => Keyword(NonReserved, SyntaxKeyword)
    case "RECURSIVE" => Keyword(NonReserved, SyntaxKeyword)
    case "REFERENCES" => Keyword(NonReserved, SyntaxKeyword)
    case "REMOVE" => Keyword(NonReserved, SyntaxKeyword)
    case "REPEATABLE" => Keyword(NonReserved, SyntaxKeyword)
    case "REPLACE" => Keyword(NonReserved, SyntaxKeyword)
    case "REPLICA" => Keyword(NonReserved, SyntaxKeyword)
    case "REPLICATION" => Keyword(NonReserved, SyntaxKeyword)
    case "REQUEST" => Keyword(NonReserved, SyntaxKeyword)
    case "RESET" => Keyword(NonReserved, SyntaxKeyword)
    case "RESOURCE" => Keyword(NonReserved, SyntaxKeyword)
    case "RESOURCES" => Keyword(NonReserved, SyntaxKeyword)
    case "RESPECT" => Keyword(NonReserved, SyntaxKeyword)
    case "RESUME" => Keyword(NonReserved, SyntaxKeyword)
    case "RETENTION" => Keyword(NonReserved, SyntaxKeyword)
    case "RETURN" => Keyword(NonReserved, SyntaxKeyword)
    case "RETURNS" => Keyword(NonReserved, SyntaxKeyword)
    case "REVOKE" => Keyword(NonReserved, SyntaxKeyword)
    case "RIGHT" => Keyword(NonReserved, SyntaxKeyword)
    case "ROLE" => Keyword(NonReserved, SyntaxKeyword)
    case "ROLLBACK" => Keyword(NonReserved, SyntaxKeyword)
    case "ROLLUP" => Keyword(NonReserved, SyntaxKeyword)
    case "ROW" => Keyword(NonReserved, SyntaxKeyword)
    case "ROWS" => Keyword(NonReserved, SyntaxKeyword)
    case "RSA" => Keyword(NonReserved, SyntaxKeyword)
    case "SAMPLE" => Keyword(NonReserved, SyntaxKeyword)
    case "SAVE" => Keyword(NonReserved, SyntaxKeyword)
    case "SCHEMA" => Keyword(NonReserved, SyntaxKeyword)
    case "SEARCH" => Keyword(NonReserved, SyntaxKeyword)
    case "SECONDARY" => Keyword(NonReserved, SyntaxKeyword)
    case "SECONDS" => Keyword(NonReserved, SyntaxKeyword)
    case "SECRET" => Keyword(NonReserved, SyntaxKeyword)
    case "SECURITY" => Keyword(NonReserved, SyntaxKeyword)
    case "SELECT" => Keyword(NonReserved, SyntaxKeyword)
    case "SEMI" => Keyword(NonReserved, SyntaxKeyword)
    case "SENSITIVE" => Keyword(NonReserved, SyntaxKeyword)
    case "SEQUENCE" => Keyword(NonReserved, SyntaxKeyword)
    case "SERVER" => Keyword(NonReserved, SyntaxKeyword)
    case "SESSION" => Keyword(NonReserved, SyntaxKeyword)
    case "SET" => Keyword(NonReserved, SyntaxKeyword)
    case "SETS" => Keyword(NonReserved, SyntaxKeyword)
    case "SHALL" => Keyword(NonReserved, SyntaxKeyword)
    case "SHARE" => Keyword(NonReserved, SyntaxKeyword)
    case "SIMPLE" => Keyword(NonReserved, SyntaxKeyword)
    case "SIZE" => Keyword(NonReserved, SyntaxKeyword)
    case "SKIP" => Keyword(NonReserved, SyntaxKeyword)
    case "SMALLINT" => Keyword(NonReserved, SyntaxKeyword)
    case "SOFTWARE" => Keyword(NonReserved, SyntaxKeyword)
    case "SOME" => Keyword(NonReserved, SyntaxKeyword)
    case "SOURCE" => Keyword(NonReserved, SyntaxKeyword)
    case "SP" => Keyword(NonReserved, SyntaxKeyword)
    case "SPACE" => Keyword(NonReserved, SyntaxKeyword)
    case "SPLIT" => Keyword(NonReserved, SyntaxKeyword)
    case "SQL" => Keyword(NonReserved, SyntaxKeyword)
    case "STAR" => Keyword(NonReserved, SyntaxKeyword)
    case "START" => Keyword(NonReserved, SyntaxKeyword)
    case "STATE" => Keyword(NonReserved, SyntaxKeyword)
    case "STATS" => Keyword(NonReserved, SyntaxKeyword)
    case "STORAGE" => Keyword(NonReserved, SyntaxKeyword)
    case "STREAM" => Keyword(NonReserved, SyntaxKeyword)
    case "STRING" => Keyword(NonReserved, SyntaxKeyword)
    case "SUBSCRIPTION" => Keyword(NonReserved, SyntaxKeyword)
    case "SUPPORTED" => Keyword(NonReserved, SyntaxKeyword)
    case "SUSPEND" => Keyword(NonReserved, SyntaxKeyword)
    case "SYSTEM" => Keyword(NonReserved, SyntaxKeyword)
    case "TABLE" => Keyword(NonReserved, SyntaxKeyword)
    case "TARGET" => Keyword(NonReserved, SyntaxKeyword)
    case "TB" => Keyword(NonReserved, SyntaxKeyword)
    case "TEMP" => Keyword(NonReserved, SyntaxKeyword)
    case "TEXT" => Keyword(NonReserved, SyntaxKeyword)
    case "THE" => Keyword(NonReserved, SyntaxKeyword)
    case "THEN" => Keyword(NonReserved, SyntaxKeyword)
    case "TIME" => Keyword(NonReserved, OptionKeyword, Some(ExpressionOption), Some(IntegerValue))
    case "TIMEOUT" => Keyword(NonReserved, OptionKeyword, Some(ExpressionOption), Some(IntegerValue))
    case "TINYINT" => Keyword(NonReserved, SyntaxKeyword)
    case "TO" => Keyword(NonReserved, SyntaxKeyword)
    case "TODO" => Keyword(NonReserved, SyntaxKeyword)
    case "TOP" => Keyword(NonReserved, SyntaxKeyword)
    case "TORT" => Keyword(NonReserved, SyntaxKeyword)
    case "TRACKING" => Keyword(NonReserved, SyntaxKeyword)
    case "TRANSACTION" => Keyword(NonReserved, SyntaxKeyword)
    case "TRANSACTIONS" => Keyword(NonReserved, SyntaxKeyword)
    case "TRIGGERS" => Keyword(NonReserved, SyntaxKeyword)
    case "TRUNCATE" => Keyword(NonReserved, SyntaxKeyword)
    case "TRY" => Keyword(NonReserved, SyntaxKeyword)
    case "TWO" => Keyword(NonReserved, SyntaxKeyword)
    case "TYPE" => Keyword(NonReserved, SyntaxKeyword)
    case "UNBOUNDED" => Keyword(NonReserved, SyntaxKeyword)
    case "UNION" => Keyword(NonReserved, SyntaxKeyword)
    case "UNIQUE" => Keyword(NonReserved, SyntaxKeyword)
    case "UNLOCK" => Keyword(NonReserved, SyntaxKeyword)
    case "UNPIVOT" => Keyword(NonReserved, SyntaxKeyword)
    case "UPDATE" => Keyword(NonReserved, SyntaxKeyword)
    case "URL" => Keyword(NonReserved, SyntaxKeyword)
    case "USE" => Keyword(NonReserved, SyntaxKeyword)
    case "USER" => Keyword(NonReserved, SyntaxKeyword)
    case "USING" => Keyword(NonReserved, SyntaxKeyword)
    case "VALIDATION" => Keyword(NonReserved, SyntaxKeyword)
    case "VALUE" => Keyword(NonReserved, SyntaxKeyword)
    case "VALUES" => Keyword(NonReserved, SyntaxKeyword)
    case "VARYING" => Keyword(NonReserved, SyntaxKeyword)
    case "VERSION" => Keyword(NonReserved, SyntaxKeyword)
    case "VIEW" => Keyword(NonReserved, SyntaxKeyword)
    case "VIEWS" => Keyword(NonReserved, SyntaxKeyword)
    case "WARRANTIES" => Keyword(NonReserved, SyntaxKeyword)
    case "WARRANTY" => Keyword(NonReserved, SyntaxKeyword)
    case "WHEN" => Keyword(NonReserved, SyntaxKeyword)
    case "WHERE" => Keyword(NonReserved, SyntaxKeyword)
    case "WHETHER" => Keyword(NonReserved, SyntaxKeyword)
    case "WINDOWS" => Keyword(NonReserved, SyntaxKeyword)
    case "WITH" => Keyword(NonReserved, SyntaxKeyword)
    case "WITHIN" => Keyword(NonReserved, SyntaxKeyword)
    case "WITHOUT" => Keyword(NonReserved, SyntaxKeyword)
    case "WORK" => Keyword(NonReserved, SyntaxKeyword)
    case "WRITE" => Keyword(NonReserved, SyntaxKeyword)
    case "XML" => Keyword(NonReserved, SyntaxKeyword)
    case "YEAR" => Keyword(NonReserved, SyntaxKeyword)

  }

  def resolveKeyword(keyword: String): Option[Keyword] = {
    commonKeywordsPf.lift(keyword.toUpperCase())
  }
}
