-- teradata sql:
CREATE SET TABLE RENAMED_TABLE, FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
    NEW_COLUMN1 CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    NEW_COLUMN2 CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('00','01','02','03','04','05')
)
PRIMARY INDEX NEW_INDEX1 ( NEW_COLUMN1, NEW_COLUMN3, NEW_COLUMN4 )
PARTITION BY RANGE_N(NEW_DATE_COLUMN BETWEEN DATE '2001-01-01' AND DATE '2030-12-31' EACH INTERVAL '1' DAY )
INDEX NEW_INDEX2 ( NEW_COLUMN1, NEW_COLUMN3, NEW_COLUMN4, NEW_DATE_COLUMN )
INDEX NEW_INDEX3 ( NEW_CITY_COLUMN );

--databricks sql:
CREATE TABLE RENAMED_TABLE (
                                      NEW_COLUMN1 STRING NOT NULL,
                                      NEW_COLUMN2 STRING
)
