-- tsql sql:
ALTER DATABASE NewDatabase
SET AUTO_CREATE_STATISTICS ON;
ALTER DATABASE NewDatabase
SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE NewDatabase
SET AUTO_UPDATE_STATISTICS_ASYNC ON;
-- REMORPH CLEANUP: DROP DATABASE NewDatabase;
