--Query type: DQL
DECLARE @ANSI_PADDING VARCHAR(3) = 'OFF';
IF ( (16 & @@OPTIONS) = 16 )
    SET @ANSI_PADDING = 'ON';
SELECT ANSI_PADDING
FROM (
    VALUES (@ANSI_PADDING)
) AS temp_result(ANSI_PADDING);
