-- tsql sql:
DECLARE @ANSI_NULLS_SETTING VARCHAR(3) = 'OFF';
IF ( (256 & @@OPTIONS) = 256 )
    SET @ANSI_NULLS_SETTING = 'ON';
SELECT value AS ANSI_NULLS_SETTING
FROM (
    VALUES (@ANSI_NULLS_SETTING)
) AS settings(value);
