-- tsql sql:
DECLARE @BITWISE_RESULT INT, @CONDITION_RESULT VARCHAR(3);
SET @BITWISE_RESULT = 256 & @@OPTIONS;
IF (@BITWISE_RESULT = 256)
    SET @CONDITION_RESULT = 'ON';
ELSE
    SET @CONDITION_RESULT = 'OFF';
SELECT *
FROM (
    VALUES (@BITWISE_RESULT, @CONDITION_RESULT)
) AS temp_result (BITWISE_RESULT, CONDITION_RESULT);
