--Query type: DML
DECLARE @XACT_ABORT VARCHAR(3) = 'OFF';
DECLARE @OPTIONS INT = 16384;
IF ( (16384 & @OPTIONS) = 16384 ) SET @XACT_ABORT = 'ON';
WITH CTE AS (
    SELECT 1 AS XACT_ABORT
)
SELECT @XACT_ABORT AS XACT_ABORT FROM CTE;
-- REMORPH CLEANUP: DROP TABLE CTE;
