--Query type: DQL
WITH temp_result AS (
    SELECT 'customer' AS TABLE_SCHEMA, 'customer' AS TABLE_NAME
    UNION ALL
    SELECT 'orders', 'orders'
)
SELECT TABLE_SCHEMA, TABLE_NAME, IDENT_SEED(CONCAT(TABLE_SCHEMA, '.', TABLE_NAME)) AS IDENT_SEED
FROM temp_result
WHERE IDENT_SEED(CONCAT(TABLE_SCHEMA, '.', TABLE_NAME)) IS NOT NULL;