name: Docs Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Must match semantic version tags like 'v1.2.3'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    name: Build Docusaurus
    runs-on:
      group: databrickslabs-protected-runner-group
      labels: linux-ubuntu-latest
    environment: release
    defaults:
      run:
        working-directory: docs/lakebridge
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: docs/lakebridge/yarn.lock # need to put the lockfile path explicitly

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/lakebridge/build  # The directory to upload as an artifact

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    defaults:
      run:
        working-directory: docs/lakebridge

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on:
      group: databrickslabs-protected-runner-group
      labels: linux-ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
